/**
 * RAZZ MOBILES - Data & Inventory Layer
 * Kanchipuram, Tamil Nadu
 * Lavender & White Design Theme
 * Includes real high-resolution local photography for all models and items
 */

const RAZZ_DATA = {
  storeInfo: {
    name: "RAZZ MOBILES",
    tagline: "Your Trusted Mobile Store & Service Center in Kanchipuram",
    locationName: "Gandhi Road, Kanchipuram",
    address: "42-A, Gandhi Road, Opp. Municipal Complex, Kanchipuram, Tamil Nadu - 631501",
    landmark: "Just 3 mins from Kanchipuram Central Bus Stand",
    phone: "+91 98421 23456",
    altPhone: "+91 94432 78901",
    whatsapp: "919842123456",
    email: "contact@razzmobiles.in",
    workingHours: {
      weekdays: "Mon - Sat: 9:30 AM – 9:30 PM",
      sunday: "Sunday: 10:00 AM – 8:00 PM"
    },
    googleMapsUrl: "https://maps.google.com/?q=Gandhi+Road+Kanchipuram+Tamil+Nadu",
    established: "2011",
    stats: {
      happyCustomers: "15,000+",
      mobilesRepaired: "28,000+",
      sparesGenuine: "100%",
      avgRepairMins: "30 Mins"
    }
  },

  smartphones: [
    {
      id: "iphone-16-pro",
      name: "Apple iPhone 16 Pro Max",
      brand: "Apple",
      condition: "Brand New",
      badge: "Flagship 2026",
      price: 144900,
      originalPrice: 154900,
      image: "assets/images/phone_iphone16.jpg",
      ram: "8 GB",
      storage: "256 GB / 512 GB",
      display: "6.9\" Super Retina XDR OLED, 120Hz ProMotion",
      camera: "48MP Fusion + 48MP Ultra-wide + 12MP 5x Telephoto",
      battery: "4685 mAh (All-day Battery)",
      processor: "Apple A18 Pro (3nm)",
      color: "Desert Titanium, Natural Titanium, White Titanium",
      inStock: true,
      rating: 4.9,
      reviewsCount: 42,
      accentColor: "#8B5CF6",
      warranty: "1 Year Official Apple India Warranty"
    },
    {
      id: "samsung-s24-ultra",
      name: "Samsung Galaxy S24 Ultra 5G",
      brand: "Samsung",
      condition: "Brand New",
      badge: "AI Powered Flagship",
      price: 129999,
      originalPrice: 139999,
      image: "assets/images/phone_s24ultra.jpg",
      ram: "12 GB",
      storage: "256 GB / 512 GB",
      display: "6.8\" Dynamic LTPO AMOLED 2X, 120Hz, 2600 nits",
      camera: "200MP + 50MP Periscope + 10MP Tele + 12MP Ultra-wide",
      battery: "5000 mAh (45W Fast Charging)",
      processor: "Snapdragon 8 Gen 3 for Galaxy",
      color: "Titanium Gray, Titanium Violet, Titanium Yellow",
      inStock: true,
      rating: 4.9,
      reviewsCount: 56,
      accentColor: "#7C3AED",
      warranty: "1 Year Samsung India Warranty + S-Pen Included"
    },
    {
      id: "oneplus-12",
      name: "OnePlus 12 5G",
      brand: "OnePlus",
      condition: "Brand New",
      badge: "Top Performance",
      price: 64999,
      originalPrice: 69999,
      image: "assets/images/phone_oneplus.jpg",
      ram: "16 GB",
      storage: "512 GB",
      display: "6.82\" 2K ProXDR Display, 120Hz LTPO4",
      camera: "50MP Sony LYT-808 + 64MP 3x Periscope + 48MP Ultra-wide",
      battery: "5400 mAh (100W SUPERVOOC Charge)",
      processor: "Snapdragon 8 Gen 3",
      color: "Silky Black, Flowy Emerald",
      inStock: true,
      rating: 4.8,
      reviewsCount: 38,
      accentColor: "#6D28D9",
      warranty: "1 Year OnePlus Official Warranty"
    },
    {
      id: "iphone-15",
      name: "Apple iPhone 15",
      brand: "Apple",
      condition: "Brand New",
      badge: "Bestseller",
      price: 69900,
      originalPrice: 79900,
      image: "assets/images/phone_iphone16.jpg",
      ram: "6 GB",
      storage: "128 GB",
      display: "6.1\" Super Retina XDR OLED, Dynamic Island",
      camera: "48MP Main + 12MP Ultra Wide with 2x Telephoto",
      battery: "3349 mAh (USB-C Fast Charging)",
      processor: "Apple A16 Bionic",
      color: "Pink, Blue, Lavender, Black, Green",
      inStock: true,
      rating: 4.9,
      reviewsCount: 68,
      accentColor: "#8B5CF6",
      warranty: "1 Year Official Apple Warranty"
    },
    {
      id: "vivo-x100-pro",
      name: "Vivo X100 Pro 5G",
      brand: "Vivo",
      condition: "Brand New",
      badge: "Zeiss Optics",
      price: 89999,
      originalPrice: 96999,
      image: "assets/images/phone_vivo.jpg",
      ram: "16 GB",
      storage: "512 GB",
      display: "6.78\" 1.5K AMOLED 120Hz LTPO Curving Display",
      camera: "50MP 1-inch Sony IMX989 + 50MP APO Telephoto + 50MP Ultra-wide",
      battery: "5400 mAh (100W FlashCharge)",
      processor: "MediaTek Dimensity 9300",
      color: "Asteroid Black, Sunset Orange",
      inStock: true,
      rating: 4.8,
      reviewsCount: 29,
      accentColor: "#7C3AED",
      warranty: "1 Year Vivo Brand Warranty"
    },
    {
      id: "nothing-phone-2a",
      name: "Nothing Phone (2a) Plus 5G",
      brand: "Nothing",
      condition: "Brand New",
      badge: "Iconic Glyph UI",
      price: 27999,
      originalPrice: 29999,
      image: "assets/images/phone_nothing.jpg",
      ram: "8 GB / 12 GB",
      storage: "256 GB",
      display: "6.7\" Flexible AMOLED, 120Hz, 1300 nits",
      camera: "50MP OIS Main + 50MP Ultra Wide + 50MP Selfie",
      battery: "5000 mAh (50W Fast Charge)",
      processor: "MediaTek Dimensity 7350 Pro 5G",
      color: "Metallic Grey, Milk White",
      inStock: true,
      rating: 4.7,
      reviewsCount: 44,
      accentColor: "#6D28D9",
      warranty: "1 Year Brand Warranty"
    },
    {
      id: "samsung-s23-certified",
      name: "Samsung Galaxy S23 5G (Certified Pre-Owned)",
      brand: "Samsung",
      condition: "Certified Used",
      badge: "Value Deal",
      price: 43999,
      originalPrice: 74999,
      image: "assets/images/phone_used_s23.jpg",
      ram: "8 GB",
      storage: "128 GB / 256 GB",
      display: "6.1\" Dynamic AMOLED 2X, 120Hz Compact Design",
      camera: "50MP OIS + 10MP 3x Telephoto + 12MP Ultra-wide",
      battery: "3900 mAh (Battery Health 98%+)",
      processor: "Snapdragon 8 Gen 2 Mobile Platform",
      color: "Phantom Black, Cream, Lavender",
      inStock: true,
      rating: 4.8,
      reviewsCount: 31,
      accentColor: "#7C3AED",
      warranty: "6 Months RAZZ Mobiles In-Store Guarantee"
    },
    {
      id: "iphone-13-certified",
      name: "Apple iPhone 13 (Certified Pre-Owned)",
      brand: "Apple",
      condition: "Certified Used",
      badge: "Budget Premium",
      price: 36999,
      originalPrice: 59900,
      image: "assets/images/phone_iphone13.jpg",
      ram: "4 GB",
      storage: "128 GB",
      display: "6.1\" Super Retina XDR OLED",
      camera: "12MP Dual Camera with Sensor-shift OIS",
      battery: "3240 mAh (Battery Health 92%+)",
      processor: "Apple A15 Bionic",
      color: "Midnight, Starlight, Blue, Pink",
      inStock: true,
      rating: 4.9,
      reviewsCount: 85,
      accentColor: "#8B5CF6",
      warranty: "6 Months RAZZ Store Warranty + 32-Point Inspection"
    },
    {
      id: "xiaomi-14",
      name: "Xiaomi 14 (Leica Optics)",
      brand: "Xiaomi",
      condition: "Brand New",
      badge: "Leica Master",
      price: 59999,
      originalPrice: 69999,
      image: "assets/images/phone_xiaomi.jpg",
      ram: "12 GB",
      storage: "512 GB",
      display: "6.36\" 1.5K LTPO AMOLED 120Hz Ultra-Compact",
      camera: "50MP Light Fusion 900 + 50MP Floating Tele + 50MP Ultra-wide",
      battery: "4610 mAh (90W HyperCharge)",
      processor: "Snapdragon 8 Gen 3",
      color: "Jade Green, White, Black",
      inStock: true,
      rating: 4.8,
      reviewsCount: 22,
      accentColor: "#6D28D9",
      warranty: "1 Year Xiaomi India Warranty"
    },
    {
      id: "realme-gt-6",
      name: "Realme GT 6 5G (AI Flagship Killer)",
      brand: "Realme",
      condition: "Brand New",
      badge: "Speed King",
      price: 38999,
      originalPrice: 42999,
      image: "assets/images/phone_oneplus.jpg",
      ram: "12 GB",
      storage: "256 GB",
      display: "6.78\" 8T LTPO AMOLED, 6000 nits Peak Brightness",
      camera: "50MP Sony LYT-808 OIS + 50MP Telephoto",
      battery: "5500 mAh (120W Ultra Charge)",
      processor: "Snapdragon 8s Gen 3",
      color: "Fluid Silver, Razor Green",
      inStock: true,
      rating: 4.7,
      reviewsCount: 35,
      accentColor: "#7C3AED",
      warranty: "1 Year Realme Warranty"
    },
    {
      id: "motorola-edge-50-pro",
      name: "Motorola Edge 50 Pro 5G",
      brand: "Motorola",
      condition: "Brand New",
      badge: "Pantone Validated",
      price: 31999,
      originalPrice: 36999,
      image: "assets/images/phone_motorola.jpg",
      ram: "12 GB",
      storage: "256 GB",
      display: "6.7\" 1.5K pOLED 144Hz 3D Curved Screen",
      camera: "50MP OIS AI Camera + 10MP 3x Telephoto + 13MP Macro",
      battery: "4500 mAh (125W TurboPower)",
      processor: "Snapdragon 7 Gen 3",
      color: "Luxe Lavender, Moonlight Pearl, Black Beauty",
      inStock: true,
      rating: 4.7,
      reviewsCount: 27,
      accentColor: "#8B5CF6",
      warranty: "1 Year Motorola India Warranty"
    },
    {
      id: "oppo-reno-12-pro",
      name: "Oppo Reno 12 Pro 5G",
      brand: "Oppo",
      condition: "Brand New",
      badge: "AI Portrait Expert",
      price: 36999,
      originalPrice: 40999,
      image: "assets/images/phone_vivo.jpg",
      ram: "12 GB",
      storage: "256 GB",
      display: "6.7\" Quad Curved AMOLED 120Hz Gorilla Glass 7i",
      camera: "50MP Sony LYT-600 OIS + 50MP Portrait Telephoto",
      battery: "5000 mAh (80W SUPERVOOC)",
      processor: "MediaTek Dimensity 7300 Energy",
      color: "Sunset Gold, Space Brown",
      inStock: true,
      rating: 4.6,
      reviewsCount: 19,
      accentColor: "#7C3AED",
      warranty: "1 Year Brand Warranty"
    }
  ],

  accessories: [
    {
      id: "acc-1",
      name: "Apple 20W USB-C Fast Power Adapter",
      category: "chargers",
      categoryName: "Chargers",
      brand: "Apple Original",
      price: 1899,
      originalPrice: 2200,
      image: "assets/images/acc_charger_apple.jpg",
      rating: 4.9,
      warranty: "1 Year Apple Warranty",
      badge: "100% Genuine",
      description: "Official Apple 20W adapter for super-fast charging for all iPhone and iPad models.",
      icon: "zap"
    },
    {
      id: "acc-2",
      name: "Samsung 45W GaN Super Fast Charger 2.0",
      category: "chargers",
      categoryName: "Chargers",
      brand: "Samsung Original",
      price: 2499,
      originalPrice: 3499,
      image: "assets/images/acc_charger_apple.jpg",
      rating: 4.9,
      warranty: "1 Year Samsung Warranty",
      badge: "Ultra Fast",
      description: "Original 45W adapter supporting Power Delivery 3.0 PPS for S24 Ultra, S23 series, and Z Fold.",
      icon: "zap"
    },
    {
      id: "acc-3",
      name: "Titan 9H Curved Edge Sapphire Glass Screen Guard",
      category: "tempered-glass",
      categoryName: "Tempered Glass",
      brand: "ShieldPro",
      price: 399,
      originalPrice: 699,
      image: "assets/images/acc_glass.jpg",
      rating: 4.8,
      warranty: "Free In-Store Bubble-Free Fit",
      badge: "Military Drop Test",
      description: "Oleophobic anti-fingerprint coating with electroplated crystal edge protection for all models.",
      icon: "shield"
    },
    {
      id: "acc-4",
      name: "AirArmor MagSafe Luxury Frosted Case",
      category: "cases",
      categoryName: "Phone Cases",
      brand: "AeroShield",
      price: 599,
      originalPrice: 1299,
      image: "assets/images/acc_case.jpg",
      rating: 4.8,
      warranty: "Non-Yellowing Guarantee",
      badge: "MagSafe Ready",
      description: "Strong N52 neodymium magnets, shock-absorbent TPU bumper with soft lavender tactile buttons.",
      icon: "smartphone"
    },
    {
      id: "acc-5",
      name: "20,000mAh 65W PD Laptop & Mobile Power Bank",
      category: "power-banks",
      categoryName: "Power Banks",
      brand: "Anker / Ambrane",
      price: 2699,
      originalPrice: 3999,
      image: "assets/images/acc_powerbank.jpg",
      rating: 4.9,
      warranty: "1 Year Replacement Warranty",
      badge: "Flight Approved",
      description: "Triple port output, charges iPhone 15 from 0 to 50% in just 25 minutes, with digital LED display.",
      icon: "battery-charging"
    },
    {
      id: "acc-6",
      name: "OnePlus Buds Pro 2 / 3 ANC Earbuds",
      category: "earphones",
      categoryName: "Earphones",
      brand: "OnePlus",
      price: 8999,
      originalPrice: 11999,
      image: "assets/images/acc_airpods.jpg",
      rating: 4.8,
      warranty: "1 Year Brand Warranty",
      badge: "Dynaudio Tuned",
      description: "Up to 50dB active noise cancellation, spatial audio, dual drivers, and 44-hour battery endurance.",
      icon: "headphones"
    },
    {
      id: "acc-7",
      name: "Apple AirPods Pro (2nd Gen, USB-C)",
      category: "earphones",
      categoryName: "Earphones",
      brand: "Apple",
      price: 21499,
      originalPrice: 24900,
      image: "assets/images/acc_airpods.jpg",
      rating: 5.0,
      warranty: "1 Year Official Apple Care",
      badge: "H2 Chip Flagship",
      description: "Active noise cancellation, transparency mode, precision tracking case, and lossless audio support.",
      icon: "headphones"
    },
    {
      id: "acc-8",
      name: "Boat Stone 352 Pro Bluetooth Speaker",
      category: "speakers",
      categoryName: "Bluetooth Speakers",
      brand: "boAt",
      price: 1599,
      originalPrice: 2999,
      image: "assets/images/acc_speaker.jpg",
      rating: 4.7,
      warranty: "1 Year Brand Warranty",
      badge: "IPX7 Waterproof",
      description: "10W RMS immersive sound, deep bass punch, RGB dynamic lights, and 12-hour continuous party play.",
      icon: "volume-2"
    },
    {
      id: "acc-9",
      name: "Samsung Galaxy Watch 6 Bluetooth 44mm",
      category: "smartwatches",
      categoryName: "Smart Watches",
      brand: "Samsung",
      price: 18999,
      originalPrice: 33999,
      image: "assets/images/acc_watch.jpg",
      rating: 4.8,
      warranty: "1 Year Brand Warranty",
      badge: "ECG & Sleep AI",
      description: "Super AMOLED Sapphire crystal glass, body composition analysis, heart rate monitor, and Wear OS.",
      icon: "watch"
    },
    {
      id: "acc-10",
      name: "Heavy-Duty Braided 100W USB-C to C Cable (2M)",
      category: "cables",
      categoryName: "USB Cables",
      brand: "RAZZ Signature",
      price: 349,
      originalPrice: 699,
      image: "assets/images/acc_cable.jpg",
      rating: 4.8,
      warranty: "6 Months Replacement",
      badge: "Unbreakable Fiber",
      description: "Reinforced Kevlar braided wire capable of 480Mbps data transfer and fast charging up to 100W.",
      icon: "activity"
    },
    {
      id: "acc-11",
      name: "MagSafe 15W Fast Wireless Magnetic Car Charger & Mount",
      category: "car-chargers",
      categoryName: "Car Chargers",
      brand: "Baseus",
      price: 1499,
      originalPrice: 2499,
      image: "assets/images/acc_carmount.jpg",
      rating: 4.7,
      warranty: "6 Months Warranty",
      badge: "360° Rotation",
      description: "Clamps securely into AC vents with intelligent heat dissipation and ultra-firm magnetic lock.",
      icon: "navigation"
    },
    {
      id: "acc-12",
      name: "Ergonomic Foldable Aluminum Mobile & Tablet Desk Stand",
      category: "stands",
      categoryName: "Mobile Stands",
      brand: "ProStand",
      price: 449,
      originalPrice: 899,
      image: "assets/images/acc_stand.jpg",
      rating: 4.8,
      warranty: "Lifetime Structure Warranty",
      badge: "Heavy Metal Base",
      description: "Dual axis angle adjustment with anti-slip silicone cushions, ideal for Zoom calls and binge watching.",
      icon: "maximize-2"
    }
  ],

  services: [
    {
      id: "screen-replacement",
      name: "Screen & Display Replacement",
      icon: "smartphone",
      image: "assets/images/srv_screen.jpg",
      time: "30 - 45 Mins",
      warranty: "90 Days Replacement Warranty",
      startingPrice: 1299,
      popular: true,
      description: "Original & high-grade OLED/AMOLED/LCD screen replacement for cracked glass, lines, or touch failure.",
      symptoms: [
        "Cracked or shattered outer glass",
        "Vertical green or white lines on display",
        "Touch not responding or ghost touch",
        "Completely black screen with vibrating sound"
      ],
      includes: "Free 9H Tempered Glass installation + dust cleanup"
    },
    {
      id: "battery-replacement",
      name: "Original Battery Replacement",
      icon: "battery-charging",
      image: "assets/images/srv_battery.jpg",
      time: "20 - 30 Mins",
      warranty: "6 Months Warranty",
      startingPrice: 899,
      popular: true,
      description: "Restore 100% battery health and full day backup using OEM certified high-density lithium polymer cells.",
      symptoms: [
        "Battery draining unusually fast",
        "Phone shutting down at 20% or 30%",
        "Swollen or bulging back panel",
        "Device heating up excessively during use"
      ],
      includes: "Safe battery disposal & thermal pad resealing"
    },
    {
      id: "charging-port",
      name: "Charging Port & Jack Repair",
      icon: "zap",
      image: "assets/images/repair_lab.jpg",
      time: "25 - 40 Mins",
      warranty: "90 Days Warranty",
      startingPrice: 599,
      popular: false,
      description: "Fix loose connection, slow charging, or unrecognised USB-C / Lightning connectors with precision micro-soldering.",
      symptoms: [
        "Cable needs to be held at an angle to charge",
        "Slow charging or 'Moisture detected' warnings",
        "Phone not recognized on computer",
        "Debris or bent pins inside socket"
      ],
      includes: "Ultrasonic port deep cleaning & flex testing"
    },
    {
      id: "speaker-mic",
      name: "Speaker, Mic & Receiver Service",
      icon: "volume-2",
      image: "assets/images/repair_lab.jpg",
      time: "30 Mins",
      warranty: "90 Days Warranty",
      startingPrice: 499,
      popular: false,
      description: "Restore crystal clear voice calls and booming audio volume with speaker/mic repairs and acoustic mesh cleanup.",
      symptoms: [
        "Caller cannot hear your voice clearly",
        "Low call earpiece volume even at maximum",
        "Crackling, distorted or muffled ringtones",
        "Headphone jack or stereo speaker mute"
      ],
      includes: "Acoustic mesh sterilization and speaker calibration"
    },
    {
      id: "camera-repair",
      name: "Camera Lens & Sensor Repair",
      icon: "camera",
      image: "assets/images/srv_screen.jpg",
      time: "45 Mins",
      warranty: "90 Days Warranty",
      startingPrice: 799,
      popular: false,
      description: "Fix cracked rear camera glass lens, shaky OIS focus issues, black camera screen, or blurry photographs.",
      symptoms: [
        "Cracked or scratched outer camera glass",
        "Camera rattling, vibrating or unable to autofocus",
        "Camera app crashing or showing black screen",
        "Dust spots or purple streaks inside lens"
      ],
      includes: "Optical chamber dust-free clean room servicing"
    },
    {
      id: "water-damage",
      name: "Liquid & Water Damage Diagnosis",
      icon: "droplet",
      image: "assets/images/srv_water.jpg",
      time: "60 - 90 Mins",
      warranty: "Diagnostic Guarantee",
      startingPrice: 699,
      popular: false,
      description: "Urgent ultrasonic motherboard de-oxidation, corrosion removal, short-circuit recovery, and data preservation.",
      symptoms: [
        "Phone dropped in water, tea, or rain",
        "Device dead or boot-looping after moisture",
        "Fog or water droplets behind camera lenses",
        "Device overheating when plugged in"
      ],
      includes: "Full IC thermal imaging check and motherboard wash"
    },
    {
      id: "motherboard-ic",
      name: "Motherboard & Micro-Soldering (Chip Level)",
      icon: "cpu",
      image: "assets/images/srv_motherboard.jpg",
      time: "Same Day / 24 Hours",
      warranty: "60 Days Warranty",
      startingPrice: 1499,
      popular: false,
      description: "Advanced BGA reballing, power IC replacement, audio IC fix, network signal repair, and dead mobile revival.",
      symptoms: [
        "Completely dead phone that won't turn on",
        "No network / 'Searching...' / No SIM detected",
        "CPU / RAM reballing for auto-restart issues",
        "NAND storage corruption / error 4013"
      ],
      includes: "Schematic level oscilloscope fault diagnosis"
    },
    {
      id: "software-unlock",
      name: "Software, OS Flashing & Data Recovery",
      icon: "hard-drive",
      image: "assets/images/repair_lab.jpg",
      time: "30 - 60 Mins",
      warranty: "Service Guarantee",
      startingPrice: 399,
      popular: false,
      description: "Official firmware flashing, stuck on Apple / Android logo fix, software crash repair, pattern/PIN recovery, and safe data migration.",
      symptoms: [
        "Phone stuck in boot loop or recovery mode",
        "Forgot screen lock PIN or pattern",
        "System update failed or corrupted",
        "Need safe data transfer to a brand new phone"
      ],
      includes: "Complete privacy and data confidentiality protocol"
    }
  ],

  whyChooseUs: [
    {
      title: "100% Genuine OEM Spares",
      desc: "We only source authentic, quality-inspected original grade parts for screens, batteries, and internal modules.",
      icon: "shield-check"
    },
    {
      title: "Express 30-Min Service",
      desc: "Most screen and battery replacements are completed right in front of you while you wait comfortably in our lounge.",
      icon: "clock"
    },
    {
      title: "Transparent & Honest Pricing",
      desc: "Zero hidden charges. Complete estimate provided after free diagnostic inspection before we start any repair.",
      icon: "award"
    },
    {
      title: "15+ Years Local Trust",
      desc: "Serving thousands of satisfied customers across Kanchipuram district with unmatched craftsmanship since 2011.",
      icon: "users"
    },
    {
      title: "90-Day Hassle-Free Warranty",
      desc: "Every repair is backed by our in-store warranty card for total peace of mind and complete satisfaction.",
      icon: "thumbs-up"
    }
  ],

  reviews: [
    {
      id: "rev-1",
      name: "Karthik Subramanian",
      location: "Gandhi Road, Kanchipuram",
      rating: 5,
      date: "2 days ago",
      comment: "My iPhone 14 Pro Max display cracked after a fall. The service center quoted 3 weeks, but RAZZ Mobiles replaced it within 40 minutes with original quality screen! Clean lavender showroom and friendly staff.",
      verified: true,
      service: "Screen Replacement"
    },
    {
      id: "rev-2",
      name: "Priya Sundaram",
      location: "Near Ekambareswarar Temple",
      rating: 5,
      date: "1 week ago",
      comment: "Bought a certified pre-owned Samsung S23 here. The phone was in pristine condition with 98% battery health. Got a great exchange value for my old phone too. Highly recommended mobile store in Kanchi!",
      verified: true,
      service: "Phone Purchase & Exchange"
    },
    {
      id: "rev-3",
      name: "Mohammed Farooq",
      location: "Ennaikaran Street, Kanchipuram",
      rating: 5,
      date: "2 weeks ago",
      comment: "My OnePlus 11 stopped charging suddenly. The technician carefully diagnosed a damaged charging port pin and fixed it for just Rs. 650. Very honest pricing and fast service. No unnecessary part changes.",
      verified: true,
      service: "Charging Port Repair"
    },
    {
      id: "rev-4",
      name: "Deepak Narayanan",
      location: "Collectorate Road, Kanchipuram",
      rating: 5,
      date: "3 weeks ago",
      comment: "Best collection of genuine MagSafe cases, tempered glass, and 65W GaN chargers in Kanchipuram. You don't have to travel to Chennai for premium smartphone accessories anymore.",
      verified: true,
      service: "Accessories Purchase"
    },
    {
      id: "rev-5",
      name: "Ananya Raman",
      location: "Chinna Kanchipuram",
      rating: 5,
      date: "1 month ago",
      comment: "Water damaged my Vivo phone in heavy rain. Brought it immediately to RAZZ Mobiles; they cleaned the motherboard ultrasonically and saved all my precious wedding photos. Forever grateful to the team!",
      verified: true,
      service: "Water Damage Repair"
    },
    {
      id: "rev-6",
      name: "Venkatesh R.",
      location: "Railway Station Road, Kanchipuram",
      rating: 5,
      date: "1 month ago",
      comment: "Got my battery replaced for iPhone 11. Battery health is now 100% and backup lasts all day. Clean work, quick turnaround, and warranty card given. Best technician in town.",
      verified: true,
      service: "Battery Replacement"
    }
  ]
};

if (typeof window !== 'undefined') {
  window.RAZZ_DATA = RAZZ_DATA;
}
